package com.blog.model;

import com.blog.model.base.BaseXAdmindev;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XAdmindev extends BaseXAdmindev<XAdmindev> {
	public static final XAdmindev dao = new XAdmindev().dao();

}
