package com.blog.model;

import com.blog.model.base.BaseXArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XArticle extends BaseXArticle<XArticle> {
	public static final XArticle dao = new XArticle().dao();
	
	
}
