package com.blog.model;

import com.blog.model.base.BaseXDev;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XDev extends BaseXDev<XDev> {
	public static final XDev dao = new XDev().dao();
	
}
