package com.blog.model;

import com.blog.model.base.BaseXFriendlylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XFriendlylink extends BaseXFriendlylink<XFriendlylink> {
	public static final XFriendlylink dao = new XFriendlylink().dao();
	

}
