package com.blog.model;

import com.blog.model.base.BaseXResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XResource extends BaseXResource<XResource> {
	public static final XResource dao = new XResource().dao();
}
