package com.blog.model;

import com.blog.model.base.BaseXTips;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XTips extends BaseXTips<XTips> {
	public static final XTips dao = new XTips().dao();
	

}
