package com.blog.model;

import com.blog.model.base.BaseXTypenav;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XTypenav extends BaseXTypenav<XTypenav> {
	public static final XTypenav dao = new XTypenav().dao();
	
	
}
