package com.blog.model;

import com.blog.model.base.BaseXUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XUser extends BaseXUser<XUser> {
	public static final XUser dao = new XUser().dao();
}
