package com.blog.model;

import com.blog.model.base.BaseXUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XUserinfo extends BaseXUserinfo<XUserinfo> {
	public static final XUserinfo dao = new XUserinfo().dao();
	
}
