package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXResource<M extends BaseXResource<M>> extends Model<M> implements IBean {

	public M setRId(java.lang.Integer rId) {
		set("r_id", rId);
		return (M)this;
	}

	public java.lang.Integer getRId() {
		return getInt("r_id");
	}

	public M setRName(java.lang.String rName) {
		set("r_name", rName);
		return (M)this;
	}

	public java.lang.String getRName() {
		return getStr("r_name");
	}

	public M setRUrl(java.lang.String rUrl) {
		set("r_url", rUrl);
		return (M)this;
	}

	public java.lang.String getRUrl() {
		return getStr("r_url");
	}

	public M setRImagepath(java.lang.String rImagepath) {
		set("r_imagePath", rImagepath);
		return (M)this;
	}

	public java.lang.String getRImagepath() {
		return getStr("r_imagePath");
	}

	public M setRDemourl(java.lang.String rDemourl) {
		set("r_demoUrl", rDemourl);
		return (M)this;
	}

	public java.lang.String getRDemourl() {
		return getStr("r_demoUrl");
	}

	public M setRType(java.lang.String rType) {
		set("r_type", rType);
		return (M)this;
	}

	public java.lang.String getRType() {
		return getStr("r_type");
	}

	public M setRUsername(java.lang.String rUsername) {
		set("r_userName", rUsername);
		return (M)this;
	}

	public java.lang.String getRUsername() {
		return getStr("r_userName");
	}

	public M setRSubheading(java.lang.String rSubheading) {
		set("r_subHeading", rSubheading);
		return (M)this;
	}

	public java.lang.String getRSubheading() {
		return getStr("r_subHeading");
	}

}
