package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXTypenav<M extends BaseXTypenav<M>> extends Model<M> implements IBean {

	public M setTId(java.lang.Integer tId) {
		set("t_id", tId);
		return (M)this;
	}

	public java.lang.Integer getTId() {
		return getInt("t_id");
	}

	public M setTTypename(java.lang.String tTypename) {
		set("t_typeName", tTypename);
		return (M)this;
	}

	public java.lang.String getTTypename() {
		return getStr("t_typeName");
	}

}
