package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXFriendlylink<M extends BaseXFriendlylink<M>> extends Model<M> implements IBean {

	public M setXLinkid(java.lang.Integer xLinkid) {
		set("x_linkId", xLinkid);
		return (M)this;
	}

	public java.lang.Integer getXLinkid() {
		return getInt("x_linkId");
	}

	public M setXLinkname(java.lang.String xLinkname) {
		set("x_linkName", xLinkname);
		return (M)this;
	}

	public java.lang.String getXLinkname() {
		return getStr("x_linkName");
	}

	public M setXLinkurl(java.lang.String xLinkurl) {
		set("x_linkUrl", xLinkurl);
		return (M)this;
	}

	public java.lang.String getXLinkurl() {
		return getStr("x_linkUrl");
	}

	public M setXLinkimgsrc(java.lang.String xLinkimgsrc) {
		set("x_linkImgSrc", xLinkimgsrc);
		return (M)this;
	}

	public java.lang.String getXLinkimgsrc() {
		return getStr("x_linkImgSrc");
	}

	public M setXLinkdescription(java.lang.String xLinkdescription) {
		set("x_linkDescription", xLinkdescription);
		return (M)this;
	}

	public java.lang.String getXLinkdescription() {
		return getStr("x_linkDescription");
	}

}
