package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXTips<M extends BaseXTips<M>> extends Model<M> implements IBean {

	public M setTId(java.lang.Integer tId) {
		set("t_id", tId);
		return (M)this;
	}

	public java.lang.Integer getTId() {
		return getInt("t_id");
	}

	public M setTContent(java.lang.String tContent) {
		set("t_content", tContent);
		return (M)this;
	}

	public java.lang.String getTContent() {
		return getStr("t_content");
	}

	public M setTSort(java.lang.Integer tSort) {
		set("t_sort", tSort);
		return (M)this;
	}

	public java.lang.Integer getTSort() {
		return getInt("t_sort");
	}

}
