package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXUserinfo<M extends BaseXUserinfo<M>> extends Model<M> implements IBean {

	public M setIId(java.lang.Integer iId) {
		set("i_id", iId);
		return (M)this;
	}

	public java.lang.Integer getIId() {
		return getInt("i_id");
	}

	public M setIUsername(java.lang.String iUsername) {
		set("i_userName", iUsername);
		return (M)this;
	}

	public java.lang.String getIUsername() {
		return getStr("i_userName");
	}

	public M setIImgsrc(java.lang.String iImgsrc) {
		set("i_imgSrc", iImgsrc);
		return (M)this;
	}

	public java.lang.String getIImgsrc() {
		return getStr("i_imgSrc");
	}

}
