package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXArticle<M extends BaseXArticle<M>> extends Model<M> implements IBean {

	public M setAId(java.lang.Integer aId) {
		set("a_id", aId);
		return (M)this;
	}

	public java.lang.Integer getAId() {
		return getInt("a_id");
	}

	public M setAUsername(java.lang.String aUsername) {
		set("a_userName", aUsername);
		return (M)this;
	}

	public java.lang.String getAUsername() {
		return getStr("a_userName");
	}

	public M setATitle(java.lang.String aTitle) {
		set("a_title", aTitle);
		return (M)this;
	}

	public java.lang.String getATitle() {
		return getStr("a_title");
	}

	public M setASubheading(java.lang.String aSubheading) {
		set("a_subHeading", aSubheading);
		return (M)this;
	}

	public java.lang.String getASubheading() {
		return getStr("a_subHeading");
	}

	public M setAArticle(java.lang.String aArticle) {
		set("a_article", aArticle);
		return (M)this;
	}

	public java.lang.String getAArticle() {
		return getStr("a_article");
	}

	public M setACreatetime(java.util.Date aCreatetime) {
		set("a_createTime", aCreatetime);
		return (M)this;
	}

	public java.util.Date getACreatetime() {
		return get("a_createTime");
	}

	public M setAType(java.lang.String aType) {
		set("a_type", aType);
		return (M)this;
	}

	public java.lang.String getAType() {
		return getStr("a_type");
	}

	public M setAMsgcount(java.lang.Integer aMsgcount) {
		set("a_msgCount", aMsgcount);
		return (M)this;
	}

	public java.lang.Integer getAMsgcount() {
		return getInt("a_msgCount");
	}

	public M setAViews(java.lang.Integer aViews) {
		set("a_views", aViews);
		return (M)this;
	}

	public java.lang.Integer getAViews() {
		return getInt("a_views");
	}

	public M setAThumbnail(java.lang.String aThumbnail) {
		set("a_thumbnail", aThumbnail);
		return (M)this;
	}

	public java.lang.String getAThumbnail() {
		return getStr("a_thumbnail");
	}

}
